# Generated by Django 3.2.6 on 2021-08-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo',
            new_name='codigo_curso',
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
